version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: attendance-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: attendance-redis
    restart: always
    ports:
      - "6379:6379"

  gateway:
    build: ./backend/gateway
    container_name: gateway
    env_file:
      - ./backend/gateway/.env
    ports:
      - "8000:8000"
    depends_on:
      - auth-service
      - student-service
      - recognition-service
      - attendance-service

  auth-service:
    build: ./backend/services/auth-service
    container_name: auth-service
    env_file:
      - ./backend/services/auth-service/.env
    depends_on:
      - postgres

  student-service:
    build: ./backend/services/student-service
    container_name: student-service
    env_file:
      - ./backend/services/student-service/.env
    depends_on:
      - postgres

  recognition-service:
    build: ./backend/services/recognition-service
    container_name: recognition-service
    env_file:
      - ./backend/services/recognition-service/.env
    depends_on:
      - redis

  attendance-service:
    build: ./backend/services/attendance-service
    container_name: attendance-service
    env_file:
      - ./backend/services/attendance-service/.env
    depends_on:
      - postgres
      - redis

  frontend:
    build: ./frontend
    container_name: attendance-frontend
    env_file:
      - ./frontend/.env
    ports:
      - "5173:5173"
    depends_on:
      - gateway

volumes:
  postgres_data:
